
<section class="organization row" itemscope itemtype="http://schema.org/Organization">

    <img class="span3" itemprop="image" src="http://www.ecomdev.org/wp-content/themes/ecomdev/images/logo.png" alt="logo of EcomDev" />

    <div class="offset1 span2">
        <div itemprop="name">EcomDev</div>
        <div itemprop="url"><a href="http://www.ecomdev.org">www.ecomdev.org</a></div>
    </div>

    <div class="span2" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
        <div><span itemprop="streetAddress">Duivenkamp 645</span>,</div>
        <div><span itemprop="addressLocality">Maarssen, Netherlands</span></div>
        <span itemprop="postalCode">3607 BR</span>
    </div>

    <div class="span2">
        <div itemprop="telephone">+380 67 323 9033</div>
        <div itemprop="telephone">+380 63 787 1538</div>
        <a href="mailto:info@ecomdev.org" itemprop="email">info@ecomdev.org</a>
    </div>

</section>
